# PR triggers in ADO are configured using branch policies. This section is only for GitHub.
# pr: none

trigger:
- public/*

variables:
- template: settings/docs.yml

jobs:
- job:
  pool:
    vmImage: windows-latest
  workspace:
    clean: all
  variables:
    DestRepoUrl: https://github.com/macborow/MixedReality-UXTools-Unreal.git
    SrcRepoDir: $(Build.SourcesDirectory)
    DstRepoDir: $(Build.ArtifactStagingDirectory)\dstrepo
    SrcBranch: $(Build.SourceBranch)
    UXTSourceDir: $(Build.SourcesDirectory)
  steps:
  - checkout: self
    clean: true
    submodules: true

  - template: templates\docs.yml
    parameters:
      SourceRepoDir: $(SrcRepoDir)
      DocsRepoDir: $(DstRepoDir)
      DocsBranchName: gh-pages  # branch to which docs should be committed
      PAT: $(GitHub.PAT)
      email: $(GitHub.email)
      username: $(GitHub.username)
      DestRepoUrl: $(DestRepoUrl)
      WebScriptsBranch: public/0.9.x  # branch with the latest index.html and web folder (TODO: switch back to master when merged)
      commit: and(succeeded(),
                  not(eq(variables['Build.Reason'], 'PullRequest')))
